In [1]:
import torch

In [2]:
dropout_layer = torch.nn.Dropout(p=0.1)

In [3]:
a = torch.tensor([1,2,3,4,5,6], dtype=torch.float)

In [4]:
dropout_layer.train()

Dropout(p=0.1, inplace=False)

In [5]:
dropout_layer(a)

tensor([1.1111, 2.2222, 3.3333, 4.4444, 5.5556, 0.0000])

In [6]:
a

tensor([1., 2., 3., 4., 5., 6.])

In [7]:
dropout_layer.eval()

Dropout(p=0.1, inplace=False)

In [8]:
dropout_layer(a)

tensor([1., 2., 3., 4., 5., 6.])